server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
    profiles:
      active:
        - "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934