#version: "3.8"

x-network-deploy-services: &network-deploy-services
  networks:
    - eazybank

x-microservice-base-config: &microservice-base-config
  <<: *network-deploy-services
  deploy:
    resources:
      limits:
        memory: 700m
  environment:
    SPRING_RABBITMQ_HOST: "rabbit"

x-microservice-configserver-config: &microservice-configserver-config
  <<: *microservice-base-config
  environment:
    SPRING_PROFILES_ACTIVE: default
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"

services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    <<: *network-deploy-services

  configserver:
    image: "rahulmore1113/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    <<: *microservice-base-config

  accounts:
    image: "rahulmore1113/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    <<: *microservice-configserver-config

  loans:
    image: "rahulmore1113/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    <<: *microservice-configserver-config

  cards:
    image: "rahulmore1113/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    <<: *microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"
